In [ ]:
# KNN
import numpy as np
from collections import Counter
import pandas as pd


In [ ]:
from sklearn.datasets import  load_diabetes
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [ ]:
#1) load dataset
data = load_diabetes()
X = data.data
Y= data.target

In [ ]:
#1) load dataset
data = load_diabetes()
X = data.data
Y= data.target

print("Original type of Y:", type(Y))
print("Original dtype of Y:", Y.dtype)

Y = Y.astype(int)

print("New type of Y:", type(Y))
print("New dtype of Y:", Y.dtype)

Original type of Y: <class 'numpy.ndarray'>
Original dtype of Y: float64
New type of Y: <class 'numpy.ndarray'>
New dtype of Y: int64


In [ ]:
# 3️⃣ Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [ ]:
# 4️⃣ Feature Scaling (IMPORTANT for KNN)
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Apply knn
knn = KNeighborsClassifier(
    n_neighbors=5,
    metric='minkowski'
)

knn.fit(X_train, Y_train)

KNeighborsClassifier()

In [ ]:
# 6️⃣ Prediction
y_pred = knn.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# 7️⃣ Model Evaluation
mse = mean_squared_error(Y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, y_pred)

print("MSE :", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MSE : 7256.730337078651
RMSE: 85.18644456178842
R2 Score: -0.369672044427648


# logistic Regression

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


In [ ]:
#load dataset
data = load_diabetes()
X = data.data
Y= data.target

print("Original type of Y:", type(Y))
print("Original dtype of Y:", Y.dtype)

Y = Y.astype(int)

print("New type of Y:", type(Y))
print("New dtype of Y:", Y.dtype)

Original type of Y: <class 'numpy.ndarray'>
Original dtype of Y: float64
New type of Y: <class 'numpy.ndarray'>
New dtype of Y: int64


In [ ]:
print("Dataser.shape:",X.shape)
print("classes:",np.unique(Y))

Dataser.shape: (442, 10)
classes: [ 25  31  37  39  40  42  43  44  45  47  48  49  50  51  52  53  54  55
  57  58  59  60  61  63  64  65  66  67  68  69  70  71  72  73  74  75
  77  78  79  80  81  83  84  85  86  87  88  89  90  91  92  93  94  95
  96  97  98  99 100 101 102 103 104 107 108 109 110 111 113 114 115 116
 118 120 121 122 123 124 125 126 127 128 129 131 132 134 135 136 137 138
 139 140 141 142 143 144 145 146 147 148 150 151 152 153 154 155 156 158
 160 161 162 163 164 166 167 168 170 171 172 173 174 175 177 178 179 180
 181 182 183 184 185 186 187 189 190 191 192 195 196 197 198 199 200 201
 202 206 208 209 210 212 214 215 216 217 219 220 221 222 225 229 230 232
 233 235 236 237 241 242 243 244 245 246 248 249 252 253 257 258 259 261
 262 263 264 265 268 270 272 273 274 275 276 277 279 280 281 283 288 292
 293 295 296 297 302 303 306 308 310 311 317 321 332 336 341 346]


In [ ]:
#2) Train-test split
X_train,X_test,Y_train,Y_test=train_test_split(
    X,Y,test_size=0.2,random_state=42
)

In [ ]:
# feature scaling (important for logistic regression)
scaler=StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# create and train model
model=LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression()

In [ ]:
#5) Predictions
y_prediction = model.predict(X_test)

In [ ]:
# Accuracy
from sklearn.metrics import accuracy_score
acc = accuracy_score(Y_test, y_prediction)
print("Accuracy:",acc)

Accuracy: 0.0


In [ ]:
from sklearn.metrics import confusion_matrix

#7) confusion matrix
conf_matrix = confusion_matrix(Y_test,y_prediction)
print("Confusion Matrix:")
conf_matrix

Confusion Matrix:


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
#8) classification matrix
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,y_prediction)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

          37       0.00      0.00      0.00       1.0
          39       0.00      0.00      0.00       0.0
          42       0.00      0.00      0.00       1.0
          48       0.00      0.00      0.00       2.0
          49       0.00      0.00      0.00       0.0
          52       0.00      0.00      0.00       2.0
          53       0.00      0.00      0.00       0.0
          55       0.00      0.00      0.00       0.0
          59       0.00      0.00      0.00       0.0
          60       0.00      0.00      0.00       1.0
          61       0.00      0.00      0.00       1.0
          63       0.00      0.00      0.00       2.0
          64       0.00      0.00      0.00       1.0
          65       0.00      0.00      0.00       0.0
          67       0.00      0.00      0.00       1.0
          68       0.00      0.00      0.00       1.0
          69       0.00      0.00      0.00       1.0
    

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_

In [ ]:

threshold = 0.3
Y_prob = model.predict_proba(X_test)[:,1]
Y_custom = (Y_prob>=threshold).astype(int)
print("\nFirst 10 predicted probabilities:\n",Y_prob[:10])
print("\nFirst 10 predicted classes:\n",Y_custom[:10])


First 10 predicted probabilities:
 [4.57263623e-04 6.41221213e-03 1.37069899e-04 1.51275747e-05
 1.10435067e-03 1.02511648e-03 1.70787590e-04 4.68906788e-05
 3.82322351e-04 1.31954545e-03]

First 10 predicted classes:
 [0 0 0 0 0 0 0 0 0 0]


In [ ]:
# sigmoid function
import numpy as np
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [ ]:
m = 0.8 # weight
c = -3 # intercept(bias)


In [ ]:
x = 6 # number of spam words

In [ ]:
z = m*x+c

In [ ]:
print("z value:",z)

z value: 1.8000000000000007


In [ ]:
probability=sigmoid(z)
print("Spam Probability:", probability)

Spam Probability: 0.8581489350995123


In [ ]:
if probability >=0.5:
    print("Prediction:SPAM")
else:
    print("Prediction:NOT SPAM")

Prediction:SPAM


# Liblinear Solver

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [ ]:
#1) load dataset
data = load_diabetes()
x = data.data
y= data.target

In [ ]:
#2) Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
#Step 3: Train–Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [ ]:
#Step 4: Apply Logistic Regression with liblinear
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    solver='liblinear',
    penalty='l2'
)

model.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [ ]:
#Step 5: Prediction
y_pred = model.predict(X_test)

In [ ]:
# Step 6: Model Evaluation
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

        37.0       0.00      0.00      0.00       1.0
        39.0       0.00      0.00      0.00       0.0
        42.0       0.00      0.00      0.00       1.0
        48.0       0.00      0.00      0.00       2.0
        52.0       0.00      0.00      0.00       2.0
        53.0       0.00      0.00      0.00       0.0
        55.0       0.00      0.00      0.00       0.0
        59.0       0.00      0.00      0.00       0.0
        60.0       0.00      0.00      0.00       1.0
        61.0       0.00      0.00      0.00       1.0
        63.0       0.00      0.00      0.00       2.0
        64.0       0.00      0.00      0.00       1.0
        65.0       0.00      0.00      0.00       0.0
        67.0       0.00      0.00      0.00       1.0
        68.0       0.00      0.00      0.00       1.0
 

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_

# lbfgs solver

In [ ]:
# 1️⃣ Import libraries
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [ ]:
# 2️⃣ Load dataset
data = load_diabetes()
X = data.data
y = data.target

In [ ]:
#  Feature scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
#  Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [ ]:
# 6 Logistic Regression with lbfgs
model = LogisticRegression(
    solver='lbfgs',
    penalty='l2',
    max_iter=1000
)

model.fit(X_train, y_train)


LogisticRegression(max_iter=1000)

In [ ]:
#  Prediction
y_pred = model.predict(X_test)


In [ ]:
# 8️⃣ Model evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


Accuracy: 0.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

        37.0       0.00      0.00      0.00       1.0
        39.0       0.00      0.00      0.00       0.0
        42.0       0.00      0.00      0.00       1.0
        48.0       0.00      0.00      0.00       2.0
        49.0       0.00      0.00      0.00       0.0
        52.0       0.00      0.00      0.00       2.0
        53.0       0.00      0.00      0.00       0.0
        55.0       0.00      0.00      0.00       0.0
        59.0       0.00      0.00      0.00       0.0
        60.0       0.00      0.00      0.00       1.0
        61.0       0.00      0.00      0.00       1.0
        63.0       0.00      0.00      0.00       2.0
        64.0       0.00      0.00      0.00       1.0
        65.0       0.00      0.00      0.00       0.0
        67.0       0.00      0.00      0.00       1.0
 

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_